# Generated by Django 5.1 on 2024-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplymodel',
            name='apply_image',
            field=models.ImageField(null=True, upload_to='Media/apply_image'),
        ),
    ]
