# Generated by Django 5.0.1 on 2024-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_jobapplymodel_apply_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='Skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics_design')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics_design')], max_length=100, null=True),
        ),
    ]
