# Generated by Django 5.0.1 on 2024-10-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_skills_jobapplymodel_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics_design')], max_length=100, null=True),
        ),
    ]
