# Generated by Django 5.0.1 on 2024-10-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_jobmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='CompanyName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
